---
title: "dataFinalProcess"
output: html_document
date: "2025-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data + Libraries

```{r}
source("../functions(new).R")
library(VennDiagram)
library(Seurat)
isoform_reference = readRDS("../../Data/Isoform/LebrigandIsoform/GSE121891_unnormalized_ref.rds")
isoform_spatial = readRDS("../../Data/Isoform/LebrigandIsoform/GSE153859_MOB.rds")
```

Get different spatial data

```{r}
gene_shortread = t(isoform_spatial@assays$Spatial$counts) # 918 pixels x 31053 genes
gene_longread = t(isoform_spatial@assays$ISOG$counts) # 918 pixels x 18724 genes
isoform_longread = t(isoform_spatial@assays$ISO$counts) # 918 pixels x 23560 isoforms

## Question: Is he sure that this represents each row is a particular pixel? Their rownames 
##           seem more like DNA barcodes e.g. TTCGGGACTAATCGCG-1
## Answer: Yes it is the actual coordinates, can see via `isoform_spatial@images$slice1@coordinates`
## Follow up question: Why is coordinates represented in DNA barcode???
```

Reduce down to gene level

```{r}
isoform_longread_rep = isoform_longread

# Sorts colnames of isoform_longread to gene-wise (23560 isoform -> 13291 unique genes )
# i.e. some cols with duplicate gene names
colnames(isoform_longread_rep) <- sub("\\..*$", "", colnames(isoform_longread_rep))

# df dim: 918 pixel x 23560 gene
df <- as.data.frame(isoform_longread_rep)
# reduced dim: 918 pixel x 13291 unique gene
isoform_longread_reduced = matrix(0, nrow = nrow(isoform_longread_rep), 
                                  ncol = length(unique(colnames(df))))
rownames(isoform_longread_reduced) = rownames(isoform_longread_rep)
colnames(isoform_longread_reduced) = unique(colnames(df))
for (gene in colnames(isoform_longread_reduced)) {
  # Summing adding all the columns in df that has the same gene colname together
  # Effectively adding vectors of dim 918 x 1 + 918 x 1 + ... -> Achieved via rowSum
  isoform_longread_reduced[,gene] = rowSums(df[,which(names(df)==gene),drop=F])
}

```





Get some other data
```{r}
spatial_meta = isoform_spatial@images$slice1@coordinates
```

Save meta data
```{r}
saveRDS(spatial_meta, "../../Data/Isoform/LebrigandIsoform/mob_metadata.rds")
```


Spatially variable gene selection
```{r}
# Tries to identify genes that have expression vary in a spatially structured way
# Test: Moran's I statistic
# Dataset: Across 3 datasets
isoform_spatial <- FindSpatiallyVariableFeatures(
  isoform_spatial,
  assay = "Spatial",
  selection.method = "moransi"
)

isoform_spatial <- FindSpatiallyVariableFeatures(
  isoform_spatial,
  assay = "ISOG",
  selection.method = "moransi"
)

isoform_spatial <- FindSpatiallyVariableFeatures(
  isoform_spatial,
  assay = "ISO",
  selection.method = "moransi"
)
```






Get spatially variable genes out
```{r}
order_df <- function(df) {
  return(df[order(df$moransi.spatially.variable.rank), ])
}

# Filtering for top 10000 spatially ranked 'units' by MoransI test
spatial_top10000 = which(isoform_spatial@assays$Spatial@meta.features$moransi.spatially.variable.rank <= 10000) # Top 10000 of 31053
isog_top10000 = which(isoform_spatial@assays$ISOG@meta.features$moransi.spatially.variable.rank <= 10000) # Top 10000 of 18724
iso_top10000 = which(isoform_spatial@assays$ISO@meta.features$moransi.spatially.variable.rank <= 10000) # Top 10000 of 23560


# Taking metafeatures (all 4x MoransI statistics) of top 10000 genes
spatial_topgenes = isoform_spatial@assays$Spatial@meta.features[spatial_top10000,]
isog_topgenes = isoform_spatial@assays$ISOG@meta.features[isog_top10000,]
iso_topgenes = isoform_spatial@assays$ISO@meta.features[iso_top10000,]

# Orders the matrix in order of highest -> lowest MoransI values
# Remember MoransI = 1 (complete clustering), MoransI = complete checkered square randomness
spatial_topgenes = order_df(spatial_topgenes)
isog_topgenes = order_df(isog_topgenes)
iso_topgenes = order_df(iso_topgenes)

```



```{r}
iso_topgenes_rep = as.matrix(iso_topgenes)
# Looking for just the gene names in the isoform level matrix
rownames(iso_topgenes_rep) = sub("\\..*$", "", rownames(iso_topgenes_rep))
# Filters for the top 1000 unique gene names in the top 10000 isoform by MoransiI test
wanted_genes = unique(rownames(iso_topgenes_rep))[1:1000]
saveRDS(isoform_longread_reduced[,wanted_genes], "../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_reduced.rds")
```



Get overlapping genes

```{r}
# Calling the genes in reference tissue sample: 18560
reference_genes = colnames(isoform_reference)


# Overlap of 8753 genes between reference and SR spatial out of 10000
# Vector of 8753 gene names
spatial_overlap = intersect(reference_genes, rownames(spatial_topgenes))
spatial_topgene_left = order_df(spatial_topgenes[spatial_overlap,])

# Overlap of 7857 genes between reference and LR gene output of 10000
# Vector of 7857 gene names
isog_overlap = intersect(reference_genes, rownames(isog_topgenes))
isog_topgene_left = order_df(isog_topgenes[isog_overlap,])

isoform_dictionary = list()
# Separates into effectively a 10000 long list of list of 2 elements: gene and isoform
# Structure: [[g1, g1i1], [g2, g2i1]]
# Note that: Note that multiple lists may have the same gene (not grouped together yet)
rowname_sep = strsplit(rownames(iso_topgenes), split = "\\.\\.")
gene_names = c()
isoform_names = c()
isoform_to_keep = c()

for (i in 1:length(rowname_sep)) {
  # Current gene name for this given isoform
  curr_g = rowname_sep[[i]][1]
  gene_names = c(gene_names, rowname_sep[[i]][1])
  
  # Pseudo-equivalent of intersect(reference, ST data) as above
  # Overlap of 6580 genes between reference and LR isoform (but looking at gene) output of 10000
  if (curr_g %in% reference_genes) {
    # Isoform dictionary[[]] Creates dictionary of all isoforms possessed by this current gene
    # 6580 genes
    isoform_dictionary[[curr_g]] = c(isoform_dictionary[[curr_g]], rowname_sep[[i]][2])
    
    # List of all isoforms kept
    # 8784 isoforms
    isoform_to_keep = c(isoform_to_keep, rownames(iso_topgenes)[i])
  }
  # List of all 10000 isoforms
  isoform_names = c(isoform_names, rowname_sep[[i]][2])
  
}
iso_topgenes_left = order_df(iso_topgenes[isoform_to_keep,])
```


Final top 1000 genes

```{r}
# List of top 1000 gene names
spatial_top1000 = rownames(spatial_topgene_left)[1:1000]
isog_top1000 = rownames(isog_topgene_left)[1:1000]
iso_top1000 = c()
genes_captured = c()
rowname_sep = strsplit(rownames(iso_topgenes_left), split = "\\.\\.")
# List of top 1000 genes captured
for (i in 1:nrow(iso_topgenes_left)) {
  if (!rowname_sep[[i]][1] %in% genes_captured) {
    # Adds genes_captured if not in current list
    genes_captured = c(genes_captured, rowname_sep[[i]][1])
    iso_top1000 = c(iso_top1000, rownames(iso_topgenes_left)[i])
  } else {
    iso_top1000 = c(iso_top1000, rownames(iso_topgenes_left)[i])
  }
  if (length(genes_captured) == 1000) {
    break
  }
}

# Venn diagram overlap of the top genes captures for all methods
venn.plot <- draw.triple.venn(
     area1 = 1000,
     area2 = 1000,
     area3 = 1000,
     n12 = length(intersect(spatial_top1000, isog_top1000)),
     n23 = length(intersect(isog_top1000, genes_captured)),
     n13 = length(intersect(spatial_top1000, genes_captured)),
     n123 = length(Reduce(intersect, list(spatial_top1000, isog_top1000, genes_captured))),
     category = c("Gene Shortread", "Gene Longread", "Isoform Longread"),
     fill = c("red", "green", "blue")
 )

venn.plot
```


```{r}
# Filters matrix to 918 pixels x 1000 SR genes
spatial_final = gene_shortread[,spatial_top1000]
# List of 34 CT for these 1000 with at least 1 positive value
# i.e. Effectivel removes 4 CTs with 0 gene count across all top 1000 genes
positive_count = names(which(rowSums(isoform_reference[,spatial_top1000]) > 0))
# Renormalise spatial reference so that each row sums to 1
# Reduces to a 34 CT x 1000 gene matrix
spatial_ref = isoform_reference[positive_count,spatial_top1000]/rowSums(isoform_reference[positive_count,spatial_top1000])

isog_final = gene_longread[,isog_top1000]
# Reduces to a 34 CT x 1000 gene matrix
positive_count = names(which(rowSums(isoform_reference[,isog_top1000]) > 0))
isog_ref = isoform_reference[positive_count,isog_top1000]/rowSums(isoform_reference[positive_count,isog_top1000])

isodict_final = list()
rowname_sep = strsplit(iso_top1000, split = "\\.\\.")
for (i in 1:length(rowname_sep)) {
  curr_g = rowname_sep[[i]][1]
  isodict_final[[curr_g]] = c(isodict_final[[curr_g]], paste("..",rowname_sep[[i]][2],sep=""))
}

iso_final = isoform_longread[,iso_top1000]
# Reduces to a 34 CT x 1000 gene matrix
positive_count = names(which(rowSums(isoform_reference[,genes_captured]) > 0))
iso_ref = isoform_reference[positive_count,genes_captured]/rowSums(isoform_reference[positive_count,genes_captured])

```


```{r}
# Don't understand this process
# Taking what is already normalise 1 rowsum
# Then finding the minimum expression value in that given row and assigning it to 0 values [i guess trying to prevent NaN?]
# But now the results are non-normalised row-wise e.g.
# > rowSums(spatial_ref)
#   Astro1   Astro2      EC1      EC2     Mes1     Mes2  MicroG1  MicroG2  MicroG3     Mono   Mural1   Mural2  MyOligo       Mφ       N1 
# 1.000027 1.000169 1.000029 1.000070 1.000025 1.000036 1.000061 1.000083 1.000446 1.000044 1.000042 1.000093 1.000019 1.000061 1.000117 
#      N10      N11      N12      N13      N14      N15      N16       N2       N3       N4       N5       N8     OEC1     OEC2     OEC3 
# 1.000023 1.000005 1.000052 1.000087 1.000022 1.000209 1.000029 1.000065 1.000099 1.000069 1.000402 1.000288 1.000040 1.000036 1.000253 
#     OEC4     OEC5      OPC     RBCs 
# 1.000026 1.000066 1.000029 1.000055 
min_spatial_ref = min(spatial_ref[spatial_ref>0])
spatial_ref[spatial_ref==0] = min_spatial_ref/10

min_isog_ref = min(isog_final[isog_final>0])
isog_ref[isog_ref==0] = min_isog_ref/10

min_iso_ref = min(iso_final[iso_final>0])
iso_ref[iso_ref==0] = min_iso_ref/10
```

Save everything

```{r}
saveRDS(spatial_final, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_SR_spatial.rds")
saveRDS(spatial_ref, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_SR_ref.rds")

saveRDS(isog_final, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_LR_spatial.rds")
saveRDS(isog_ref, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_LR_ref.rds")

saveRDS(iso_final, "../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_spatial.rds")
saveRDS(iso_ref, "../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_ref.rds")
saveRDS(isodict_final, "../../Data/Isoform/LebrigandIsoform/proc_data/iso_dict.rds")
```


# Reload

```{r}
spatial_final = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/gene_SR_spatial.rds")
spatial_ref = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/gene_SR_ref.rds")

isog_final = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/gene_LR_spatial.rds")
isog_ref = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/gene_LR_ref.rds")

iso_final = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_spatial.rds")
iso_ref = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_ref.rds")
isodict_final = readRDS("../../Data/Isoform/LebrigandIsoform/proc_data/iso_dict.rds")

```


Prior correlation

```{r}
cor_matrix_plot_gt(as.matrix(spatial_ref), title='Gene Shortread Transcription Profile')

cor_matrix_plot_gt(as.matrix(isog_ref), title='Gene Longread Transcription Profile')

cor_matrix_plot_gt(as.matrix(iso_ref), title='Isoform Longread Transcription Profile')
```


Prior constant
Start with 0.1 for all
```{r}
# Need logic also behind assigning these prior weights?
spatial_pw = rep(0.1, dim(spatial_ref)[1])
isog_pw = rep(0.1, dim(isog_ref)[1])
iso_pw = rep(0.1, dim(iso_ref)[1])
```

Save prior weights
```{r}
saveRDS(spatial_pw, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_SR_pw.rds")
saveRDS(isog_pw, "../../Data/Isoform/LebrigandIsoform/proc_data/gene_LR_pw.rds")
saveRDS(iso_pw, "../../Data/Isoform/LebrigandIsoform/proc_data/iso_LR_pw.rds")

```









