---
title: "LebrigandIsoform"
output: html_document
date: "2025-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is responsible of initial data investigation

```{r}

data = readRDS("../../Data/Isoform/LebrigandIsoform/GSE153859_MOB.rds")

```


# Analysis

```{R}
#data$nCount_Spatial
```



```{r}
# 18724 genes x 918 spots (ISOG)
# 31053 genes x 918 spots (Spatial)

data@assays$ISO$counts[1:5,1:5]
```

Genes in common

```{r}
genes_in_common = intersect(rownames(data@assays$Spatial$counts), rownames(data@assays$ISOG$counts))
```


Isoforms

```{r}
isoform_counts = data@assays$ISO$counts
isoform_names = rownames(isoform_counts)
rowname_sep = strsplit(isoform_names, split = "\\.\\.")
gene_names = c()
isoform_names = c()

for (i in 1:length(rowname_sep)) {
  gene_names = c(gene_names, rowname_sep[[i]][1])
  isoform_names = c(isoform_names, rowname_sep[[i]][2])
}

unique_genes = unique(gene_names)
unique_isoforms = unique(isoform_names)
print(paste("Total number of unique genes", length(unique_genes)))
print(paste("Total number of unique_isoforms", length(unique_isoforms)))
```

Sample some genes and its corresponding isoforms

```{r}
genes_sampled = sample(unique_genes, size = 10)
for (gene in genes_sampled) {
  gene_idx = which(gene_names == gene)
  curr_isoform = isoform_names[gene_idx]
  print(paste("Gene", gene, "has isoforms", paste(curr_isoform, collapse = " ")))
}
```

Distribution of number of different isoforms

```{r}
num_isoform = c()

for (gene in unique_genes) {
  num_isoform = c(num_isoform, length(which(gene_names == gene)))
}

isoform_counts <- table(num_isoform)

barplot(isoform_counts,
        main = "Distribution of unique isoform counts",
        xlab = "Number of unique isoforms",
        ylab = "Frequency",
        col = "skyblue",
        border = "white")

saveRDS(isoform_counts,"../../Data/LebrigandIsoform/isoform_dist.rds")

```













