---
title: "gene_level_analysis"
output: html_document
date: "2025-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import libraries and files

```{r}
source("../functions(new).R")

gene_sr_res1 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_SR_t1.rds")
gene_sr_res2 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_SR_t2.rds")
gene_sr_res3 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_SR_t3.rds")
gene_sr_res4 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_SR_t4.rds")
gene_sr_res5 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_SR_t5.rds")

metadata = readRDS("../../Data/Isoform/LebrigandIsoform/mob_metadata.rds")
```

Cell Type importance

```{r}
est_spatial_abundance = gene_sr_res3$gamma/rowSums(gene_sr_res3$gamma)
celltypeimportance <- colSums(est_spatial_abundance)
importance_df <- data.frame(
  CellType = names(celltypeimportance),
   Proportion = celltypeimportance / sum(celltypeimportance)
)

# Sort by proportion (descending)
importance_df <- importance_df[order(importance_df$Proportion, decreasing = TRUE), ]

# Ensure factor levels match sort order
importance_df$CellType <- factor(importance_df$CellType, levels = importance_df$CellType)

# Plot
ggplot(importance_df, aes(x = CellType, y = Proportion, fill = CellType)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), 
            vjust = -0.3, size = 2.5) +
  labs(
    title = "Ground Truth Relative abundance of cell types",
    y = "Proportion",
    x = "Cell Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )
```


Define Color
```{r}
colors_provide = rep('black', ncol(gene_sr_res1$gamma))
names(colors_provide) = colnames(gene_sr_res1$gamma)
colors_provide["Astro1"] = 'brown'
colors_provide["N10"] = 'steelblue'
colors_provide["N11"] = 'green'
colors_provide["N12"] = 'blue'
colors_provide["OEC1"] = 'red'
colors_provide["N14"] = 'darkorange'
colors_provide["OEC5"] = 'magenta'
colors_provide["N5"] = 'cyan'
colors_provide["N13"] = 'yellow'
colors_provide["N15"] = 'indianred1'
colors_provide["RBCs"] = 'deepskyblue'



# colors_provide['Astro1'] = 'coral3'
# colors_provide['Astro2'] = 'coral'
# colors_provide['EC1'] = 'bisque'
# colors_provide['EC2'] = 'bisque4'
# colors_provide['Mes1'] = 'chartreuse4'
# colors_provide['Mes2'] = 'chartreuse'
# colors_provide['MicroG1'] = 'purple4'
# colors_provide['MicroG2'] = 'purple2'
# colors_provide['MicroG3'] = 'purple'
# colors_provide['Mono'] = 'cadetblue1'
# colors_provide['Mural1'] = 'gold4'
# colors_provide['Mural2'] = 'gold1'
# colors_provide['MyOligo'] = 'brown'
# colors_provide['Mφ'] = 'lemonchiffon'
# colors_provide['N1'] = 'grey1'
# colors_provide['N2'] = 'grey10'
# colors_provide['N3'] = 'grey20'
# colors_provide['N4'] ='grey30'
# colors_provide['N5'] = 'grey40'
# colors_provide['N8'] = 'grey50'
# colors_provide['N10'] = 'grey60'
# colors_provide['N11'] = 'grey70'
# colors_provide['N12'] = 'grey80'
# colors_provide['N13'] = 'grey90'
# colors_provide['N14'] = 'grey100'
# colors_provide['N15'] = 'lavender'
# colors_provide['N16'] = 'linen'
# colors_provide['OEC1'] = 'hotpink'
# colors_provide['OEC2'] = 'hotpink3'
# colors_provide['OEC3'] = 'indianred1'
# colors_provide['OEC4'] = 'indianred4'
# colors_provide['OEC5'] = 'red'
# colors_provide['OPC'] = 'blue'
# colors_provide['RBCs'] = 'cyan'

 

```


```{r}
pos = matrix(0, nrow = nrow(metadata), ncol=2)
colnames(pos) = c('x', 'y')
pos[,'y'] = 25000-metadata$imagerow
pos[,'x'] = metadata$imagecol
rownames(pos) = rownames(gene_sr_res1$gamma)

vizAllTopics(gene_sr_res3$gamma/rowSums(gene_sr_res3$gamma),pos,topicCols=colors_provide,
             r = 110)
```



```{r}

gene_exp_matrix_check = matrix(0, nrow = 12, ncol = ncol(gene_sr_res1$tau))
our_est = gene_sr_res3$tau[c('Astro1','N10','N11','N12','OEC1','N14'),]
comp_w_ref = gene_sr_res3$eta[c('Astro1','N10','N11','N12','OEC1','N14'),]
rownames(gene_exp_matrix_check) = c("XAstro1", "Astro1",
                                    "XN10", "N10",
                                    "XN11", "N11",
                                    "XN12", "N12",
                                    "XOEC1", "OEC1",
                                    "XN14", "N14")
gene_exp_matrix_check[c(1,3,5,7,9,11),] = our_est/rowSums(our_est)
gene_exp_matrix_check[c(2,4,6,8,10,12),] = comp_w_ref/rowSums(comp_w_ref)
visualize_reference(gene_exp_matrix_check,want_log = F)
```














# Gene longread analysis

```{r}

gene_lr_res1 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_LR_t1.rds")
gene_lr_res2 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_LR_t2.rds")
gene_lr_res3 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_LR_t3.rds")
gene_lr_res4 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_LR_t4.rds")
gene_lr_res5 = readRDS("../../Data/Isoform/LebrigandIsoform/results/gene_LR_t5.rds")
```

Cell Type importance

```{r}
est_spatial_abundance = gene_lr_res1$gamma/rowSums(gene_lr_res1$gamma)
celltypeimportance <- colSums(est_spatial_abundance)
importance_df <- data.frame(
  CellType = names(celltypeimportance),
   Proportion = celltypeimportance / sum(celltypeimportance)
)

# Sort by proportion (descending)
importance_df <- importance_df[order(importance_df$Proportion, decreasing = TRUE), ]

# Ensure factor levels match sort order
importance_df$CellType <- factor(importance_df$CellType, levels = importance_df$CellType)

# Plot
ggplot(importance_df, aes(x = CellType, y = Proportion, fill = CellType)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), 
            vjust = -0.3, size = 2.5) +
  labs(
    title = "Ground Truth Relative abundance of cell types",
    y = "Proportion",
    x = "Cell Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )
```


Define Color
```{r}
colors_provide = rep('black', ncol(gene_sr_res1$gamma))
names(colors_provide) = colnames(gene_sr_res1$gamma)
colors_provide["N11"] = 'green'
colors_provide["N14"] = 'blue'
colors_provide["MyOligo"] = 'red'



# colors_provide['Astro1'] = 'coral3'
# colors_provide['Astro2'] = 'coral'
# colors_provide['EC1'] = 'bisque'
# colors_provide['EC2'] = 'bisque4'
# colors_provide['Mes1'] = 'chartreuse4'
# colors_provide['Mes2'] = 'chartreuse'
# colors_provide['MicroG1'] = 'purple4'
# colors_provide['MicroG2'] = 'purple2'
# colors_provide['MicroG3'] = 'purple'
# colors_provide['Mono'] = 'cadetblue1'
# colors_provide['Mural1'] = 'gold4'
# colors_provide['Mural2'] = 'gold1'
# colors_provide['MyOligo'] = 'brown'
# colors_provide['Mφ'] = 'lemonchiffon'
# colors_provide['N1'] = 'grey1'
# colors_provide['N2'] = 'grey10'
# colors_provide['N3'] = 'grey20'
# colors_provide['N4'] ='grey30'
# colors_provide['N5'] = 'grey40'
# colors_provide['N8'] = 'grey50'
# colors_provide['N10'] = 'grey60'
# colors_provide['N11'] = 'grey70'
# colors_provide['N12'] = 'grey80'
# colors_provide['N13'] = 'grey90'
# colors_provide['N14'] = 'grey100'
# colors_provide['N15'] = 'lavender'
# colors_provide['N16'] = 'linen'
# colors_provide['OEC1'] = 'hotpink'
# colors_provide['OEC2'] = 'hotpink3'
# colors_provide['OEC3'] = 'indianred1'
# colors_provide['OEC4'] = 'indianred4'
# colors_provide['OEC5'] = 'red'
# colors_provide['OPC'] = 'blue'
# colors_provide['RBCs'] = 'cyan'

 

```


```{r}
vizAllTopics(gene_lr_res1$gamma/rowSums(gene_lr_res1$gamma),pos,topicCols=colors_provide,
             r = 110)
```








