---
title: "LebrigandSTdeconvolve"
output: html_document
date: "2025-08-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data

```{r}
library(STdeconvolve)
meta = readRDS("../../Data/Isoform/LebrigandIsoform/mob_metadata.rds")
isoform_spatial = readRDS("../../Data/Isoform/LebrigandIsoform/GSE153859_MOB.rds")
```

```{r}
full_longread = t(isoform_spatial@assays$ISO@counts)
isoform_longread_rep = full_longread
colnames(isoform_longread_rep) <- sub("\\..*$", "", colnames(isoform_longread_rep))
df <- as.data.frame(isoform_longread_rep)
isoform_longread_reduced = matrix(0, nrow = nrow(isoform_longread_rep), 
                                  ncol = length(unique(colnames(df))))
rownames(isoform_longread_reduced) = rownames(isoform_longread_rep)
colnames(isoform_longread_reduced) = unique(colnames(df))
for (gene in colnames(isoform_longread_reduced)) {
  isoform_longread_reduced[,gene] = rowSums(df[,which(names(df)==gene),drop=F])
}
```

```{r}
longread_counts <- t(cleanCounts(counts = t(full_longread),
                      min.lib.size = 100,
                      min.reads = 1,
                      min.detected = 1,
                      verbose = TRUE))
longread_counts <- t(restrictCorpus(t(longread_counts),
                         removeAbove = 1.0,
                         removeBelow = 0.01,
                         alpha = 0.05,
                         plot = F,
                         verbose = TRUE))

```


```{r}
proc_meta = meta[rownames(longread_counts),]
ldas <- fitLDA(as.matrix(longread_counts), Ks = seq(5,11, by = 1),
               perc.rare.thresh = 0.05,
               plot=TRUE,
               verbose=TRUE)
```

Plot

```{r}
#my_labels <- seq(9, 25, by = 2)  # length should match your data points

# Suppress default x-axis
#plot(ldas$perplexities, xaxt = "n", type = "b",
#     xlab = "Clusters Experimented", 
#     ylab = "Perplexities", col = 'red',
#     main = "Isoform data Perplexity plot")

# Add custom x-axis
#axis(1, at = 1:length(ldas$perplexities), labels = my_labels)

```




## Get the deconvolved results out
```{r}

#optLDA <- optimalModel(models = ldas, opt = "min")

## extract pixel cell-type proportions (theta) and cell-type gene expression profiles (beta) for the given dataset
## we can also remove cell-types from pixels that contribute less than 5% of the pixel proportion
## and scale the deconvolved transcriptional profiles by 1000 
results <- getBetaTheta(ldas$models$'9',
                        perc.filt = 0.05,
                        betaScale = 1000)
deconProp <- results$theta
deconGexp <- results$beta
```


Plot

```{r}
colors_provide <- c('1'='brown', '2'='green', '3'='gold', '4'='darkblue', 
             '5'='red', '6'='yellow', '7'='black','8'='orange', '9' = 'skyblue')
colors_provide <- c('1'='red', '2'='cyan', '3'='orange', '4'='black',
             '5'='green', '6'='black', '7'='yellow','8'='brown', '9'='blue')
pos = data.frame(x = proc_meta$imagecol, y = 50000 - proc_meta$imagerow)
rownames(pos) = rownames(deconProp)

#for (i in 1:9) {
#  new_col = colors_provide
#  new_col[i] = 'red'
#  p = vizAllTopics(as.matrix(deconProp), pos=pos, r = 120, topicCols = new_col)
#  plot(p)
#}
vizAllTopics(as.matrix(deconProp), pos=pos, r = 120, topicCols = colors_provide)
```


```{r}
longread_counts_reduced <- t(cleanCounts(counts = t(isoform_longread_reduced),
                      min.lib.size = 100,
                      min.reads = 1,
                      min.detected = 1,
                      verbose = TRUE))
longread_counts_reduced <- t(restrictCorpus(t(longread_counts_reduced),
                         removeAbove = 1.0,
                         removeBelow = 0.01,
                         alpha = 0.05,
                         plot = F,
                         verbose = TRUE))
proc_meta_reduced = meta[rownames(longread_counts_reduced),]

```



```{r}
ldas_reduced <- fitLDA(as.matrix(longread_counts_reduced), Ks = seq(5,11, by = 1),
               perc.rare.thresh = 0.05,
               plot=TRUE,
               verbose=TRUE)
```


## Get the deconvolved results out
```{r}


## extract pixel cell-type proportions (theta) and cell-type gene expression profiles (beta) for the given dataset
## we can also remove cell-types from pixels that contribute less than 5% of the pixel proportion
## and scale the deconvolved transcriptional profiles by 1000 
results <- getBetaTheta(ldas_reduced$models$'11',
                        perc.filt = 0.05,
                        betaScale = 1000)
deconProp <- results$theta
deconGexp_reduced <- results$beta
```


Plot

```{r}
colors_provide <- c('1'='brown', '2'='orange', '3'='darkblue', '4'='gold',
             '5'='red', '6'='yellow', '7'='skyblue','8'='black', '9' = 'green')
colors_provide <- c('1'='yellow', '2'='orange', '3'='cyan', '4'='violet',
             '5'='red', '6'='blue', '7'='brown','8'='purple', '9'='black',
             '10'='black', '11'='green')

pos = data.frame(x = proc_meta_reduced$imagecol, y = 50000 - proc_meta_reduced$imagerow)
rownames(pos) = rownames(deconProp)

#for (i in 1:11) {
#  new_col = colors_provide
#  new_col[i] = 'red'
#  p = vizAllTopics(as.matrix(deconProp), pos=pos, r = 120, topicCols = new_col)
#  plot(p)
#}
vizAllTopics(as.matrix(deconProp), pos=pos, r = 120, topicCols = colors_provide)
```




